#  libfreebsd Makefile.uk
#
#  Authors: Daniel Tudor Bibi <daniel.bibi@unikraft.io>
#
#  Copyright (c) 2023, Unikraft GmbH. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

################################################################################
# This will reserve space within `uk_tls` for the pthread structure.
# Please refer to ./arch/Makefile.rules for more details.
# For FreeBSD 13.4.0 the size of "struct pthread" is TBD.
# We use 200 as a placeholder, same as musl.
################################################################################
ifeq ($(CONFIG_LIBFREEBSD),y)
$(eval $(call ukarch_tls_tcb_reserve,200))
endif

################################################################################
# On aarch64, we don't need a reserved block at the end of the TCB.
################################################################################
ifeq ($(CONFIG_LIBFREEBSD),y)
ifeq (arm64,$(CONFIG_UK_ARCH))
$(eval $(call aarch64_no_reserved_tcb_overlap))
endif
endif

################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libfreebsd,$(CONFIG_LIBFREEBSD)))
$(eval $(call addlib_s,libfreebsdglue,$(CONFIG_LIBFREEBSD)))

################################################################################
# Sources
################################################################################
LIBFREEBSD_VERSION=13.4-RELEASE
LIBFREEBSD_URL=https://download.freebsd.org/ftp/releases/amd64/$(LIBFREEBSD_VERSION)/src.txz
LIBFREEBSD_PATCHDIR=$(LIBFREEBSD_BASE)/patches
$(eval $(call fetch,libfreebsd,$(LIBFREEBSD_URL)))
$(eval $(call patch,libfreebsd,$(LIBFREEBSD_PATCHDIR),usr/src))

################################################################################
# Helpers
################################################################################
LIBFREEBSD_SRC=$(LIBFREEBSD_ORIGIN)/usr/src

# Additional macros for freebsd sub-libraries
include $(LIBFREEBSD_BASE)/Makefile.rules

################################################################################
# Library includes
################################################################################
FREEBSD_ARCH = $(subst x86_64,amd64,$(subst arm64,arm64,$(ARCH)))

LIBFREEBSD_GLOBAL_INCLUDES-y   += -I$(LIBFREEBSD_SRC)/include
LIBFREEBSD_GLOBAL_INCLUDES-y   += -I$(LIBFREEBSD_SRC)/sys/$(FREEBSD_ARCH)/include
LIBFREEBSD_GLOBAL_INCLUDES-y   += -I$(LIBFREEBSD_SRC)/lib/libc/include
LIBFREEBSD_GLOBAL_INCLUDES-y   += -I$(LIBFREEBSD_BASE)/include

LIBFREEBSD_COMPFLAGS-y += -I$(LIBFREEBSD_SRC)/include
LIBFREEBSD_COMPFLAGS-y += -I$(LIBFREEBSD_SRC)/sys/$(FREEBSD_ARCH)/include
LIBFREEBSD_COMPFLAGS-y += -I$(LIBFREEBSD_SRC)/lib/libc/include

CINCLUDES-$(CONFIG_LIBFREEBSD)    += $(LIBFREEBSD_GLOBAL_INCLUDES-y)
CXXINCLUDES-$(CONFIG_LIBFREEBSD)  += $(LIBFREEBSD_GLOBAL_INCLUDES-y)

################################################################################
# Global flags
################################################################################
LIBFREEBSD_HDRS_FLAGS-y += -Wno-unused-parameter
LIBFREEBSD_HDRS_FLAGS-y += -Wno-parentheses
LIBFREEBSD_HDRS_FLAGS-y += -Wno-builtin-macro-redefined

LIBFREEBSD_CFLAGS-y += -Wno-implicit-fallthrough
LIBFREEBSD_CFLAGS-$(call have_gcc) += -Wno-restrict
LIBFREEBSD_CFLAGS-$(call have_gcc) += -Wno-unused-but-set-variable
LIBFREEBSD_CFLAGS-y += -Wno-sign-compare
LIBFREEBSD_CFLAGS-y += -Wno-empty-body
LIBFREEBSD_CFLAGS-$(call have_gcc) += -Wno-maybe-uninitialized
LIBFREEBSD_CFLAGS-y += -Wno-unknown-pragmas
LIBFREEBSD_CFLAGS-y += -Wno-missing-braces
LIBFREEBSD_CFLAGS-$(call gcc_version_ge,8,0) += -Wno-cast-function-type
LIBFREEBSD_CFLAGS-$(call clang_version_ge,13,0) += -Wno-cast-function-type
LIBFREEBSD_CFLAGS-$(call have_gcc) += -Wno-format-contains-nul
LIBFREEBSD_CFLAGS-y += -Wno-type-limits
LIBFREEBSD_CFLAGS-$(call have_clang) += -Wno-macro-redefined
LIBFREEBSD_CFLAGS-$(call have_clang) += -Wno-string-plus-int
LIBFREEBSD_CFLAGS-y += -Wno-unused
LIBFREEBSD_CFLAGS-$(call have_gcc) += -Wno-old-style-declaration
LIBFREEBSD_CFLAGS-$(call clang_version_ge,15,0) += -Wno-deprecated-non-prototype
LIBFREEBSD_CFLAGS-y += -DUK_LIBC_SYSCALLS=0
LIBFREEBSD_CFLAGS-y += -D_XOPEN_SOURCE=700
LIBFREEBSD_CFLAGS-y += $(LIBFREEBSD_HDRS_FLAGS-y)
LIBFREEBSD_ASFLAGS-y += -Wno-unused-command-line-argument

LIBFREEBSD_CFLAGS-y += -ffreestanding

CFLAGS-$(CONFIG_LIBFREEBSD) += $(LIBFREEBSD_HDRS_FLAGS-y)
CXXFLAGS-$(CONFIG_LIBFREEBSD) += $(LIBFREEBSD_HDRS_FLAGS-y)

################################################################################
# OS dependencies code - Glue between Unikraft and freebsd
################################################################################
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/mem.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/__uk_init_tls.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/__uk_unmapself.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/__set_thread_area.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/arch/$(CONFIG_UK_ARCH)/__clone.S
LIBFREEBSDGLUE_SRCS-$(CONFIG_LIBPOSIX_PROCESS_VFORK) += $(LIBFREEBSD_BASE)/arch/$(CONFIG_UK_ARCH)/vfork.S

# lwIP glue code
ifeq ($(CONFIG_LIBLWIP),y)
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/lwip/getaddrinfo.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/lwip/gethostbyname.c
LIBFREEBSDGLUE_SRCS-y += $(LIBFREEBSD_BASE)/lwip/getnameinfo.c
endif

LIBFREEBSDGLUE_COMPFLAGS-y += -I$(LIBFREEBSD_SRC)/include
LIBFREEBSDGLUE_COMPFLAGS-y += -I$(LIBFREEBSD_SRC)/lib/libc/include
LIBFREEBSDGLUE_CINCLUDES += -I$(LIBFREEBSD_SRC)/lib/libc/include
LIBFREEBSDGLUE_CFLAGS-y += -Wno-unused-value

################################################################################
# freebsd code -- one external Makefile per sub-lib
################################################################################
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.csu
ifeq ($(CONFIG_LIBFREEBSD_MQ),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.mq
endif
ifeq ($(CONFIG_LIBFREEBSD_DIRENT),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.dirent
endif
ifeq ($(CONFIG_LIBFREEBSD_MISC),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.misc
endif
ifeq ($(CONFIG_LIBFREEBSD_TEMP),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.temp
endif
ifeq ($(CONFIG_LIBFREEBSD_MULTIBYTE),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.multibyte
endif
ifeq ($(CONFIG_LIBFREEBSD_PROCESS),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.process
endif
ifeq ($(CONFIG_LIBFREEBSD_MMAN),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.mman
endif
ifeq ($(CONFIG_LIBFREEBSD_STDLIB),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.stdlib
endif
ifeq ($(CONFIG_LIBFREEBSD_FCNTL),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.fcntl
endif
ifeq ($(CONFIG_LIBFREEBSD_STDIO),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.stdio
endif
ifeq ($(CONFIG_LIBFREEBSD_CONF),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.conf
endif
ifeq ($(CONFIG_LIBFREEBSD_MATH),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.math
endif
ifeq ($(CONFIG_LIBFREEBSD_AIO),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.aio
endif
ifeq ($(CONFIG_LIBFREEBSD_STAT),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.stat
endif
ifeq ($(CONFIG_LIBFREEBSD_SEARCH),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.search
endif
ifeq ($(CONFIG_LIBFREEBSD_CRYPT),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.crypt
endif
ifeq ($(CONFIG_LIBFREEBSD_SELECT),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.select
endif
ifeq ($(CONFIG_LIBFREEBSD_MALLOC),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.malloc
endif
ifeq ($(CONFIG_LIBFREEBSD_UNISTD),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.unistd
endif
ifeq ($(CONFIG_LIBFREEBSD_SIGNAL),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.signal
endif
ifeq ($(CONFIG_LIBFREEBSD_THREAD),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.thread
endif
ifeq ($(CONFIG_LIBFREEBSD_LEGACY),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.legacy
endif
ifeq ($(CONFIG_LIBFREEBSD_ENV),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.env
endif
ifeq ($(CONFIG_LIBFREEBSD_TIME),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.time
endif
ifeq ($(CONFIG_LIBFREEBSD_ERRNO),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.errno
endif
ifeq ($(CONFIG_LIBFREEBSD_IPC),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.ipc
endif
ifeq ($(CONFIG_LIBFREEBSD_PRNG),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.prng
endif
ifeq ($(CONFIG_LIBFREEBSD_LDSO),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.ldso
endif
ifeq ($(CONFIG_LIBFREEBSD_PASSWD),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.passwd
endif
ifeq ($(CONFIG_LIBFREEBSD_FENV),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.fenv
endif
ifeq ($(CONFIG_LIBFREEBSD_CTYPE),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.ctype
endif
ifeq ($(CONFIG_LIBFREEBSD_LINUX),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.linux
endif
ifeq ($(CONFIG_LIBFREEBSD_INTERNAL),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.internal
endif
ifeq ($(CONFIG_LIBFREEBSD_NETWORK),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.network
endif
ifeq ($(CONFIG_LIBFREEBSD_SCHED),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.sched
endif
ifeq ($(CONFIG_LIBFREEBSD_STRING),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.string
endif
ifeq ($(CONFIG_LIBFREEBSD_REGEX),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.regex
endif
ifeq ($(CONFIG_LIBFREEBSD_TERMIOS),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.termios
endif
ifeq ($(CONFIG_LIBFREEBSD_EXIT),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.exit
endif
ifeq ($(CONFIG_LIBFREEBSD_SETJMP),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.setjmp
endif
ifeq ($(CONFIG_LIBFREEBSD_LOCALE),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.locale
endif
ifeq ($(CONFIG_LIBFREEBSD_COMPLEX),y)
include $(LIBFREEBSD_BASE)/Makefile.uk.freebsd.complex
endif