#
# Import a sub-library of FreeBSD libc
#
# @param $(1)
#   The name of the sub-library.
# @param $(2)
#   The headers for this sub-library.
# @param $(3)
#   The source files for this sub-library.
#
define _libfreebsd_import_lib
LIBFREEBSD_SRCS-y += $(3)
endef