LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/include/errno.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/lib/libc/include/libc_private.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/sys/sys/limits.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/include/signal.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/include/stdio.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/sys/sys/syscall.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/sys/sys/resource.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/sys/sys/sysinfo.h
LIBFREEBSD_CONF_HDRS-y += $(LIBFREEBSD_SRC)/include/unistd.h

LIBFREEBSD_CONF_SRCS-y += $(LIBFREEBSD_SRC)/lib/libc/gen/confstr.c
LIBFREEBSD_CONF_SRCS-y += $(LIBFREEBSD_SRC)/lib/libc/gen/sysconf.c

$(eval $(call _libfreebsd_import_lib,conf,$(LIBFREEBSD_CONF_HDRS-y),$(LIBFREEBSD_CONF_SRCS-y)))
